# 서버 포트
server.port=8080

# H2 데이터베이스 설정
spring.datasource.url=jdbc:h2:mem:accountbookdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 웹 콘솔 활성화
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# 브라우저에서 localhost:8080/h2-console로 DB 관리 화면에 접속할 수 있게 해줌

# JPA / Hibernate 설정
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# ddl-auto=update: 자바 코드(Entity)를 수정하면 자동으로 DB 테이블 스키마를 업데이트함.
spring.jpa.show-sql=true
# show-sql=true: 실행되는 SQL 쿼리를 콘솔 창에 보기 쉽게 출력해 줌
spring.jpa.properties.hibernate.format_sql=true
No newline at end of file